version: '3.8'

services:
  backend:
    build: ./backend  # Path to your backend folder with the Dockerfile
    restart: always
    ports:
      - "8003:5000"  # Map VPS port 8003 to container port 5000
    environment:
      - DB_HOST=db
      - DB_USER=your_db_user
      - DB_PASSWORD=your_strong_password
      - DB_NAME=your_db_name
    depends_on:
      - db

  frontend:
    build: ./frontend # Path to your frontend folder with the Dockerfile
    restart: always
    ports:
      - "8004:80"    # Map VPS port 8004 to container port 80

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_db_name
      MYSQL_USER: your_db_user
      MYSQL_PASSWORD: your_strong_password
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: